name: Label PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Apply labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const rules = [
              { label: 'migrations', patterns: ['migrations/**'] },
              { label: 'tests', patterns: ['tests/**'] },
              { label: 'docs', patterns: ['docs/**'] },
            ];

            const { data: files } = await github.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            const labels = new Set();

            for (const file of files) {
              for (const rule of rules) {
                for (const pattern of rule.patterns) {
                  if (minimatch(file.filename, pattern)) {
                    labels.add(rule.label);
                  }
                }
              }
            }

            if (labels.size > 0) {
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: Array.from(labels)
              });
            }
